name: Test Suite

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: attribution_app_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5 # Adjust the Ruby version as needed

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.10.0'

    - name: Install JavaScript dependencies
      run: yarn install --frozen-lockfile

    - name: Build CSS
      run: yarn css:build  

    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      run: |
        bundle exec rails test